name: traits
channels:
  - smirarab
  - conda-forge
  - bioconda
  - defaults
  - cruizperez
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - biopython=1.79=py39h3811e60_0
  - ca-certificates=2021.10.8=ha878542_0
  - cd-hit=4.8.1=h2e03b76_5
  - debugpy=1.4.1=py39he80948d_1
  - decorator=5.1.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - epa-ng=0.3.8=h9a82719_1
  - fasttree=2.1.10=h779adbc_5
  - gappa=0.7.1=h9a82719_1
  - hmmer=3.3.2=h1b792b2_1
  - ipykernel=6.4.2=py39hef51801_0
  - ipython_genutils=0.2.0=py_1
  - iqtree=2.1.4_beta=hdcc8f71_0
  - jedi=0.18.0=py39hf3d152e_3
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libblas=3.9.0=11_linux64_openblas
  - libcblas=3.9.0=11_linux64_openblas
  - libffi=3.3=h58526e2_2
  - libgcc-ng=11.2.0=h1d223b6_8
  - libgfortran-ng=11.2.0=h69a702a_8
  - libgfortran5=11.2.0=h5c6108e_8
  - libgomp=11.2.0=h1d223b6_8
  - liblapack=3.9.0=11_linux64_openblas
  - libopenblas=0.3.17=pthreads_h8fe5266_1
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_8
  - mafft=7.490=h779adbc_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - muscle=3.8.1551=h7d875b9_6
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - numpy=1.21.2=py39hdbf815f_0
  - openssl=1.1.1l=h7f98852_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=21.3.1=pyhd8ed1ab_0
  - prodigal=2.6.3=h779adbc_3
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - python=3.9.6=h12debd9_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pyzmq=22.3.0=py39h37b5a0c_0
  - readline=8.1=h46c0cb4_0
  - seqkit=2.0.0=h9ee0642_0
  - setuptools=58.0.4=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h9cd32fc_1
  - tk=8.6.11=h27826a3_1
  - tornado=6.1=py39h3811e60_2
  - treeshrink=1.3.7=py39_0
  - trimal=1.4.1=h7d875b9_5
  - tzdata=2021a=he74cb21_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd8ed1ab_1
  - xz=5.2.5=h516909a_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zlib=1.2.11=h516909a_1010
  - pip:
    - biom-format==2.1.10
    - cachecontrol==0.12.6
    - certifi==2021.5.30
    - charset-normalizer==2.0.6
    - click==8.0.1
    - cycler==0.10.0
    - cython==0.29.24
    - docstring-parser==0.7.3
    - emperor==1.0.3
    - empress==1.2.0
    - falcon==2.0.0
    - future==0.18.2
    - ghp-import==2.0.2
    - gitdb==4.0.9
    - gitpython==3.1.24
    - h5py==3.4.0
    - hdmedians==0.14.2
    - hug==2.6.1
    - idna==3.2
    - importlib-metadata==4.8.1
    - iow==0.1.3
    - ipython==7.28.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - kiwisolver==1.3.2
    - livereload==2.6.3
    - lockfile==0.12.2
    - mako==1.1.5
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.3
    - mergedeep==1.3.4
    - mkdocs==1.2.3
    - mkdocs-material==7.3.0
    - mkdocs-material-extensions==1.0.3
    - msgpack==1.0.2
    - natsort==7.1.1
    - ncbi-acc-download==0.2.8
    - nose==1.3.7
    - packaging==21.2
    - pandas==1.3.3
    - pdocs==1.1.1
    - pillow==8.3.2
    - portray==1.7.0
    - prompt-toolkit==3.0.20
    - pyfastx==0.8.4
    - pymdown-extensions==7.1
    - pyparsing==2.4.7
    - pytz==2021.1
    - pyyaml==6.0
    - pyyaml-env-tag==0.1
    - requests==2.26.0
    - scikit-bio==0.5.6
    - scikit-learn==1.0
    - scipy==1.7.1
    - smmap==5.0.0
    - threadpoolctl==2.2.0
    - toml==0.10.2
    - traitlets==5.1.0
    - typing-extensions==3.10.0.2
    - urllib3==1.26.7
    - watchdog==2.1.6
    - yaspin==0.15.0
    - zipp==3.6.0
